title: Yanjie Xu
email: yanjie.xu5@gmail.com
description: >-
  Academic website of Yanjie Xu, a macroecologist working on biodiversity dynamics,
  conservation prioritisation, and wildlife and zoonotic diseases.
url: "https://yanjie-xu.github.io"
baseurl: ""
markdown: kramdown
permalink: /news/:year/:month/:day/:title/
timezone: Europe/Helsinki
exclude:
  - README.md
  - EDITING-GUIDE.md
  - _site-preview
  - tools
